[package]
name = "procedural-masquerade"
version = "0.1.7"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
description = "macro_rules for making proc_macro_derive pretending to be proc_macro"
documentation = "https://docs.rs/procedural-masquerade/"
repository = "https://github.com/servo/rust-cssparser"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"
doctest = false
